In [2]:
import numpy as np
#Question 1
a = np.random.random([10,1])
a

array([[0.31436766],
       [0.51982962],
       [0.47181256],
       [0.85574992],
       [0.01753044],
       [0.61748304],
       [0.31964391],
       [0.27519784],
       [0.64060778],
       [0.82873634]])

In [3]:
np.mean(a)

0.4860959091852591

# Question 2

In [4]:
b = np.random.random([20,1])
b

array([[0.17649868],
       [0.98554046],
       [0.33309999],
       [0.19111124],
       [0.55559095],
       [0.80927239],
       [0.42587404],
       [0.28322028],
       [0.23846138],
       [0.6113732 ],
       [0.88476156],
       [0.66850888],
       [0.15428266],
       [0.49081063],
       [0.8602992 ],
       [0.55832476],
       [0.71480882],
       [0.29788835],
       [0.59720158],
       [0.89100539]])

In [5]:
np.var(b)

0.06738973112065341

In [6]:
np.std(b)

0.25959532183892187

# Question 3

In [12]:
A = np.random.random([10,20])
B = np.random.random([20,25])
C = np.dot(A,B)
C

array([[4.15695095, 3.70122162, 3.25087921, 4.11573165, 4.26185011,
        4.85351263, 4.95751083, 4.13728315, 4.38007421, 4.80583927,
        5.62911042, 5.30083173, 3.56998081, 4.95490046, 4.37326572,
        4.16701084, 3.68000242, 4.83952402, 2.83405096, 5.22194192,
        4.16148197, 5.11043299, 2.76566293, 4.69308217, 4.4486565 ],
       [4.9415835 , 6.34059258, 4.20595539, 4.91454413, 5.12006694,
        4.93146227, 5.54342781, 4.64896611, 6.01243203, 6.74500329,
        7.34848309, 5.74697554, 4.39119797, 6.66981594, 5.36031971,
        5.78261652, 5.19937992, 5.91856533, 4.89519979, 6.64299946,
        5.14298144, 6.42938824, 3.36151343, 5.99182154, 6.14510821],
       [4.12831559, 4.92345518, 2.82391055, 3.72773079, 3.55721043,
        3.799846  , 3.44305384, 3.53788415, 4.64021831, 5.26684764,
        5.92033256, 4.607078  , 3.67518019, 4.60485628, 3.76882003,
        5.12577483, 5.12224341, 4.7506871 , 3.82865075, 5.31936341,
        4.60532135, 4.81193137, 3.19246802, 5.

In [13]:
C.shape

(10, 25)

In [14]:
np.sum(C)

1154.003620425961

# Question 4

In [17]:
p = np.arange(10).reshape(10,1)
print(p.T)

[[0 1 2 3 4 5 6 7 8 9]]


In [18]:
def sigmoid(p):
    return 1/(1 + np.exp(-p))
print(sigmoid(p))

[[0.5       ]
 [0.73105858]
 [0.88079708]
 [0.95257413]
 [0.98201379]
 [0.99330715]
 [0.99752738]
 [0.99908895]
 [0.99966465]
 [0.99987661]]
