In [1]:
import numpy as pd
import pandas as df
from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn import datasets
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import train_test_split

digit=datasets.load_wine()
p=digit.data
q=digit.target
p_train,p_test,q_train,q_test = train_test_split(p,q,test_size=0.3)
m1=DecisionTreeClassifier()
#m1.fit(p_train,q_train)
esti1=BaggingClassifier(base_estimator=m1)
esti1.fit(p_train,q_train)
pred1=esti1.predict(p_test)
metrics.accuracy_score(q_test,pred1)

0.8888888888888888

In [2]:
print(metrics.classification_report(q_test,pred1))

             precision    recall  f1-score   support

          0       0.87      0.93      0.90        14
          1       0.87      0.87      0.87        23
          2       0.94      0.88      0.91        17

avg / total       0.89      0.89      0.89        54



In [3]:
print(metrics.confusion_matrix(q_test,pred1))

[[13  1  0]
 [ 2 20  1]
 [ 0  2 15]]


In [4]:
esti2=RandomForestClassifier(n_estimators=100)
esti2.fit(p_train,q_train)
pred2=esti2.predict(p_test)
metrics.accuracy_score(q_test,pred2)*100

98.14814814814815

In [5]:
print(metrics.classification_report(q_test,pred2))

             precision    recall  f1-score   support

          0       0.93      1.00      0.97        14
          1       1.00      0.96      0.98        23
          2       1.00      1.00      1.00        17

avg / total       0.98      0.98      0.98        54



In [6]:
print(metrics.confusion_matrix(q_test,pred2))

[[14  0  0]
 [ 1 22  0]
 [ 0  0 17]]


In [7]:
esti3=GradientBoostingClassifier(n_estimators=100)
esti3.fit(p_train,q_train)
pred3=esti3.predict(p_test)
metrics.accuracy_score(q_test,pred3)*100

94.44444444444444

In [8]:
print(metrics.classification_report(q_test,pred3))

             precision    recall  f1-score   support

          0       0.93      0.93      0.93        14
          1       0.92      0.96      0.94        23
          2       1.00      0.94      0.97        17

avg / total       0.95      0.94      0.94        54



In [9]:
arr=[]
model1=LogisticRegression()
arr.append(("Logistic",model1))
model2=DecisionTreeClassifier()
arr.append(("Cart",model2))
model3=SVC()
arr.append(("SVM",model3))
model=VotingClassifier(arr).fit(p_test,q_test)
pred=model.predict(p_test)
metrics.accuracy_score(q_test,pred)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


1.0

In [10]:
print(metrics.classification_report(q_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        14
          1       1.00      1.00      1.00        23
          2       1.00      1.00      1.00        17

avg / total       1.00      1.00      1.00        54



In [11]:
print(metrics.confusion_matrix(q_test,pred))

[[14  0  0]
 [ 0 23  0]
 [ 0  0 17]]
