In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report
from sklearn import model_selection
from sklearn import metrics
from sklearn import datasets
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

##Probability of Sunny
S=5.0/14
##Probability of Yes
Y=9.0/14
##Probability of (Sunny/Yes)
P=3.0/9
##Probability of (Yes/Sunny)
Q=(P*Y)/S
Q

0.6

In [2]:
df=datasets.load_iris()
p=df.data
q=df.target
p_train,p_test,q_train,q_test = train_test_split(p,q,test_size=0.3)
p_train.shape , p_test.shape

((105, 4), (45, 4))

In [3]:
## Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(p,q)

GaussianNB(priors=None)

In [4]:
model.fit(p,q)

GaussianNB(priors=None)

In [5]:
pred=model.predict(p)
metrics.accuracy_score(q,pred)*100

96.0

In [6]:
print(classification_report(q,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        50
          1       0.94      0.94      0.94        50
          2       0.94      0.94      0.94        50

avg / total       0.96      0.96      0.96       150



In [7]:
print(confusion_matrix(q,pred))

[[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]


In [8]:
## Multinomial Naive Bayes 
from sklearn.naive_bayes import MultinomialNB
p_train,p_test,q_train,q_test = train_test_split(p,q,test_size=0.3)
p_train.shape , p_test.shape

((105, 4), (45, 4))

In [9]:
m=MultinomialNB()
m.fit(p,q)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [10]:
predi=m.predict(p)
metrics.accuracy_score(q,predi)*100

95.33333333333334

In [11]:
print(classification_report(q,predi))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        50
          1       0.94      0.92      0.93        50
          2       0.92      0.94      0.93        50

avg / total       0.95      0.95      0.95       150



In [12]:
print(confusion_matrix(q,predi))

[[50  0  0]
 [ 0 46  4]
 [ 0  3 47]]
