In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn import metrics
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

digit=datasets.load_digits()
p=digit.data
q=digit.target
p.shape,q.shape

((1797, 64), (1797,))

In [2]:
p=preprocessing.scale(p)
df=pd.DataFrame(p)
df.head()

0         1         2         3         4         5         6         7   \
0  0.0 -0.335016 -0.043081  0.274072 -0.664478 -0.844129 -0.409724 -0.125023   
1  0.0 -0.335016 -1.094937  0.038648  0.268751 -0.138020 -0.409724 -0.125023   
2  0.0 -0.335016 -1.094937 -1.844742  0.735366  1.097673 -0.409724 -0.125023   
3  0.0 -0.335016  0.377661  0.744919  0.268751 -0.844129 -0.409724 -0.125023   
4  0.0 -0.335016 -1.094937 -2.551014 -0.197863 -1.020657 -0.409724 -0.125023   

         8         9     ...           54        55        56        57  \
0 -0.059078 -0.624009    ...    -0.757436 -0.209785 -0.023596 -0.299081   
1 -0.059078 -0.624009    ...    -0.757436 -0.209785 -0.023596 -0.299081   
2 -0.059078 -0.624009    ...     0.259230 -0.209785 -0.023596 -0.299081   
3 -0.059078  1.879691    ...     1.072563 -0.209785 -0.023596 -0.299081   
4 -0.059078 -0.624009    ...    -0.757436 -0.209785 -0.023596 -0.299081   

         58        59        60        61        62        63  
0  0.086719  0.208293 -0.366771 -1.146647 -0.505670 -0.196008  
1 -1.089383 -0.249010  0.849632  0.548561 -0.505670 -0.196008  
2 -1.089383 -2.078218 -0.164037  1.565686  1.695137 -0.196008  
3  0.282736  0.208293  0.241430  0.379040 -0.505670 -0.196008  
4 -1.089383 -2.306869  0.849632 -0.468564 -0.505670 -0.196008  

[5 rows x 64 columns]

In [3]:
p_train,p_test,q_train,q_test = train_test_split(p,q,test_size=0.3)

In [4]:
pca = PCA(n_components=16)
principalComponents = pca.fit_transform(p)
principalComponents

array([[ 1.91422304, -0.95449914, -3.94606559, ..., -0.19430345,
         0.83108213, -0.09919926],
       [ 0.58904438,  0.92453054,  3.92455692, ..., -0.39649298,
        -0.76593039,  0.26152943],
       [ 1.30203299, -0.3171763 ,  3.02338702, ..., -0.98278747,
        -1.17313651, -0.42671305],
       ...,
       [ 1.02251981, -0.14778743,  2.47017527, ...,  0.25628273,
         0.35745526, -1.22833043],
       [ 1.07607294, -0.38095088, -2.45552182, ..., -0.7812426 ,
         0.02264604, -0.15294581],
       [-1.25771281, -2.22764899,  0.28391398, ...,  0.7430877 ,
         1.81590881, -0.21773961]])

In [5]:
p=principalComponents
p.shape,q.shape

((1797, 16), (1797,))

In [6]:
reg = LogisticRegression()
reg.fit(p_train,q_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [7]:
pred = reg.predict(p_test)

In [8]:
metrics.accuracy_score(q_test,pred)*100

96.66666666666667

In [9]:
print(confusion_matrix(q_test,pred))

[[50  0  0  0  0  0  0  0  0  0]
 [ 0 51  0  0  0  0  1  0  0  1]
 [ 0  0 63  0  0  0  0  0  0  0]
 [ 0  0  1 49  0  0  0  0  0  0]
 [ 0  1  0  0 51  0  0  0  1  1]
 [ 0  0  0  0  0 50  0  0  0  0]
 [ 1  1  0  0  0  0 57  0  0  0]
 [ 0  0  0  0  0  0  0 56  0  1]
 [ 0  3  2  1  0  0  1  0 51  0]
 [ 0  1  0  0  0  1  0  0  0 44]]


In [10]:
print(classification_report(q_test,pred))

             precision    recall  f1-score   support

          0       0.98      1.00      0.99        50
          1       0.89      0.96      0.93        53
          2       0.95      1.00      0.98        63
          3       0.98      0.98      0.98        50
          4       1.00      0.94      0.97        54
          5       0.98      1.00      0.99        50
          6       0.97      0.97      0.97        59
          7       1.00      0.98      0.99        57
          8       0.98      0.88      0.93        58
          9       0.94      0.96      0.95        46

avg / total       0.97      0.97      0.97       540

