In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn import datasets
from sklearn import metrics
from sklearn.model_selection import train_test_split

digit=datasets.load_digits()
p=digit.data
q=digit.target
p_train,p_test,q_train,q_test = train_test_split(p,q,test_size=0.4)
p_train.shape , p_test.shape

((1078, 64), (719, 64))

In [2]:
m=SVC(kernel="linear")
m.fit(p_train,q_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [3]:
pred=m.predict(p_test)
metrics.accuracy_score(q_test,pred)

0.9777468706536857

In [4]:
print(metrics.confusion_matrix(q_test,pred)) 

[[75  0  0  0  0  0  0  0  0  0]
 [ 0 70  0  0  0  0  0  0  2  0]
 [ 0  0 72  0  0  0  0  0  0  0]
 [ 0  0  0 71  0  0  0  0  0  1]
 [ 0  0  0  0 79  0  0  0  0  0]
 [ 0  0  0  0  0 75  0  0  0  1]
 [ 0  0  0  0  0  1 66  0  0  0]
 [ 0  0  0  0  2  0  0 70  0  0]
 [ 0  1  0  3  0  0  0  1 56  0]
 [ 0  0  0  0  0  2  0  1  1 69]]


In [5]:
print(metrics.classification_report(q_test,pred)) 

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        75
          1       0.99      0.97      0.98        72
          2       1.00      1.00      1.00        72
          3       0.96      0.99      0.97        72
          4       0.98      1.00      0.99        79
          5       0.96      0.99      0.97        76
          6       1.00      0.99      0.99        67
          7       0.97      0.97      0.97        72
          8       0.95      0.92      0.93        61
          9       0.97      0.95      0.96        73

avg / total       0.98      0.98      0.98       719



In [6]:
m2=SVC(kernel="poly")
m2.fit(p_train,q_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [7]:
pred2=m2.predict(p_test)
metrics.accuracy_score(q_test,pred2)*100

99.30458970792768

In [8]:
print(metrics.confusion_matrix(q_test,pred2)) 

[[75  0  0  0  0  0  0  0  0  0]
 [ 0 72  0  0  0  0  0  0  0  0]
 [ 0  0 72  0  0  0  0  0  0  0]
 [ 0  0  0 72  0  0  0  0  0  0]
 [ 0  0  0  0 79  0  0  0  0  0]
 [ 0  0  0  0  0 75  0  0  0  1]
 [ 0  0  0  0  0  0 67  0  0  0]
 [ 0  0  0  0  0  0  0 72  0  0]
 [ 0  0  0  1  0  0  0  1 59  0]
 [ 0  0  0  0  0  1  0  1  0 71]]


In [9]:
print(metrics.classification_report(q_test,pred2)) 

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        75
          1       1.00      1.00      1.00        72
          2       1.00      1.00      1.00        72
          3       0.99      1.00      0.99        72
          4       1.00      1.00      1.00        79
          5       0.99      0.99      0.99        76
          6       1.00      1.00      1.00        67
          7       0.97      1.00      0.99        72
          8       1.00      0.97      0.98        61
          9       0.99      0.97      0.98        73

avg / total       0.99      0.99      0.99       719



In [10]:
m3=SVC()
m3.fit(p_train,q_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [11]:
pred3=m3.predict(p_test)
metrics.accuracy_score(q_test,pred3)

0.3560500695410292

In [12]:
print(metrics.confusion_matrix(q_test,pred3))  

[[30  0  0  0  0  0  0  0 45  0]
 [ 0 25  0  0  0  0  0  0 47  0]
 [ 0  0 11  0  0  0  0  0 61  0]
 [ 0  0  0 35  0  0  0  0 37  0]
 [ 0  0  0  0 11  0  0  0 68  0]
 [ 0  0  0  0  0  9  0  0 67  0]
 [ 0  0  0  0  0  0 45  0 22  0]
 [ 0  0  0  0  0  0  0 19 53  0]
 [ 0  0  0  0  0  0  0  0 61  0]
 [ 0  0  0  0  0  0  0  0 63 10]]


In [14]:
print(metrics.classification_report(q_test,pred3))

             precision    recall  f1-score   support

          0       1.00      0.40      0.57        75
          1       1.00      0.35      0.52        72
          2       1.00      0.15      0.27        72
          3       1.00      0.49      0.65        72
          4       1.00      0.14      0.24        79
          5       1.00      0.12      0.21        76
          6       1.00      0.67      0.80        67
          7       1.00      0.26      0.42        72
          8       0.12      1.00      0.21        61
          9       1.00      0.14      0.24        73

avg / total       0.93      0.36      0.41       719



In [15]:
m4=SVC(kernel="sigmoid")
m4.fit(p_train,q_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [16]:
pred4=m4.predict(p_test)
metrics.accuracy_score(q_test,pred4)*100

9.318497913769123

In [17]:
print(metrics.confusion_matrix(q_test,pred3)) 

[[30  0  0  0  0  0  0  0 45  0]
 [ 0 25  0  0  0  0  0  0 47  0]
 [ 0  0 11  0  0  0  0  0 61  0]
 [ 0  0  0 35  0  0  0  0 37  0]
 [ 0  0  0  0 11  0  0  0 68  0]
 [ 0  0  0  0  0  9  0  0 67  0]
 [ 0  0  0  0  0  0 45  0 22  0]
 [ 0  0  0  0  0  0  0 19 53  0]
 [ 0  0  0  0  0  0  0  0 61  0]
 [ 0  0  0  0  0  0  0  0 63 10]]


In [18]:
print(metrics.classification_report(q_test,pred4)) 

             precision    recall  f1-score   support

          0       0.00      0.00      0.00        75
          1       0.00      0.00      0.00        72
          2       0.00      0.00      0.00        72
          3       0.00      0.00      0.00        72
          4       0.00      0.00      0.00        79
          5       0.00      0.00      0.00        76
          6       0.09      1.00      0.17        67
          7       0.00      0.00      0.00        72
          8       0.00      0.00      0.00        61
          9       0.00      0.00      0.00        73

avg / total       0.01      0.09      0.02       719



C:\Users\hp\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
